# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e02c6ef3cefa85069991340c246a6bef2581245d053a8f97f22f31051a3bca4efc835c50969fa7aa00323603ac43c50bbe935421e42694a06b7a071e6d24bcf2
  twilio_account_sid: AC56b30a6a6993c8e68b0f49457477d6e9
  twilio_token: e42a2420e9e55ec4732b10b021cc962b
  twilio_messaging_service_sid: MG770e97721a0a6ea760aaecd1b5bbf801
  twilio_number: '+16475608701'



test:
  secret_key_base: da067ebe5d1d27a7c6015f274778e81b863723fe7e0002ab6137521eb119b515a477c568e16e1380920150cdbcd042dfc80a3bdca6c0795ab8e0359cfcd20780

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
